### PR TITLE
fix out of office all day events and other all day events

### PR DESCRIPTION
**Pull request by HCAWN**
image

### CODE REVIEW

**Comment by HCAWN** [comment]
Fixes issues:
https://github.com/HCAWN/gcal-multical-event-merge/issues/6
https://github.com/HCAWN/gcal-multical-event-merge/issues/5
Latter I'm not so sure about actually will check on issue

**Comment by HCAWN** [comment]
image
actually fixes https://github.com/HCAWN/gcal-multical-event-merge/issues/5 now

**Comment by HCAWN** [comment]
image
dropdown choices for styles

**Comment by michaelblyons** [comment]
🙂 Ship it.

**Pull request merged**
